### PR TITLE
Website PR

### PR DESCRIPTION
**Pull request by Reevak05**
problem

### CODE REVIEW

**Comment by Reevak05** [comment]
wait
stop

**Comment by Reevak05** [comment]
@MetalTurtle18 @CamShaft54 I'm not able to make a PR from my gh-pages branch to this one. It just says `There isn’t anything to compare.
CamShaft54:gh-pages and Reevak05:gh-pages are entirely different commit histories.` I think you will have to just give me write access.

If you want, try deleting all the files from the IdleBot gh-pages branch because it's not supposed to have any of the normal code and we can see if that works but I doubt it will.

**Comment by MetalTurtle18** [comment]
So the way GitHub Pages works is by having another branch that has none of the actual code, just the website code?

**Comment by Reevak05** [comment]
yeah exactly

**Comment by MetalTurtle18** [comment]
@Reevak05 So why don't you clone the repo, edit that branch to contain the right files, and make a new PR

**Comment by Reevak05** [comment]
I'm not sure I understand. If I clone and remove those files, I'll have to push to a repo which I have write access to, and my fork is already set up without those files.

**Comment by MetalTurtle18** [comment]
I don't understand why it wouldn't let it merge before, I'm going to reopen it to look.

**Comment by Reevak05** [comment]
no don't @MetalTurtle18 this is from master

**Comment by MetalTurtle18** [comment]
> this is from master
Why

**Comment by Reevak05** [comment]
accident after it didn't even let me create a PR from gh-pages to gh-pages

**Comment by Reevak05** [comment]
that's why I closed it

**Comment by MetalTurtle18** [comment]
I think the problems are coming up because you asked us to create a branch AFTER you had finished everything and GitHub doesn't like merging to entirely separate branches. My only idea would be for you to pull the new gh-pages branch from here to your repo and do what you want then try to open a new PR.

**Comment by Reevak05** [comment]
alright I'll try that in a bit

**Comment by Reevak05** [comment]
it doesn't even let me pull the new gh-pages branch from this repo. I have an idea for something else though I'll try it

**Comment by Reevak05** [comment]
For chapter 3 of this GitHub adventure, turn to page #7.

**Pull request closed without merging**
